name: k3s deployment using ansible

on:
  push:
    branches:
      - main
    paths:
      - ansible/**

jobs:
  setup_runner:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login
  
      - name: Pulumi stack select
        run:  |
          pulumi stack select amirul/aws-k3s-ansible/dev
  
      - name: Pulumi refresh
        run: |
          pulumi refresh --yes
      
      - name: Save Pulumi outputs
        id: pulumi_outputs
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
            GIT_RUNNER_IP=$(pulumi stack output git_runner_public_ip)
            MASTER_IP=$(pulumi stack output master_private_ip)
            WORKER1_IP=$(pulumi stack output worker1_private_ip)
            WORKER2_IP=$(pulumi stack output worker2_private_ip)
  
            echo "GIT_RUNNER_IP=$GIT_RUNNER_IP" >> $GITHUB_ENV
            echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
            echo "WORKER1_IP=$WORKER1_IP" >> $GITHUB_ENV
            echo "WORKER2_IP=$WORKER2_IP" >> $GITHUB_ENV

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}